/*Funcion de Array con los objetos
const productos =[
    {
        id: "1",
        nombre: "Head Prestige",
        imagen:"/img/head3.webp",
        precio: 199,
        cantidad:1,
    },
    {
        id: "2",
        nombre: "Head Radical",
        imagen:"/img/head5.webp",
        precio: 149,
        cantidad: 1,
    },
    {
        id: "3",
        nombre: "Head Radical Pro",
        imagen:"/img/head6.webp",
        precio: 203,
        cantidad:1,
    },
    {
        id: "4",
        nombre: "Head Speed Pro",
        imagen:"/img/head2.webp",
        precio: 240,
        cantidad: 1,
    },
    {
        id: "5",
        nombre: "Wilson Blade 98",
        imagen:"/img/w5.jpg",
        precio: 196,
        cantidad:1,
    },
    {
        id: "6",
        nombre: "Wilson Clash",
        imagen:"/img/w7.jpg",
        precio: 197,
        cantidad: 1,
    },
    {
        id: "7",
        nombre: "Wilson Blade 100",
        imagen:"/img/w3.jpg",
        precio: 186,
        cantidad: 1,
    },
    {
        id: "8",
        nombre: "Wilson Pro Staff",
        imagen:"/img/w9.webp",
        precio: 250,
        cantidad: 1,
    },
    {
        id: "9",
        nombre: "Babolat Pure Aero",
        imagen:"/img/img1.jpg",
        precio: 198,
        cantidad:1,
    },
    {
        id: "10",
        nombre: "Babolat Boost Rafa",
        imagen:"/img/img3.jpg",
        precio: 280,
        cantidad: 1,
    },
    {
        id: "11",
        nombre: "Babolat Pure Drive",
        imagen: "/img/img2.jpg",
        precio: 205,
        cantidad: 1,
    },
    {
        id: "Pelota1",
        nombre: "Pelota Babolat",
        imagen: "/img/pelotababolat.webp",
        precio: 6,
        cantidad: 1,
    },
    {
        id: "Pelota2",
        nombre: "Pelota Dunlop",
        imagen: "/img/pelotadunlop.jpg",
        precio: 5,
        cantidad: 1,
    },
    {
        id: "Pelota3",
        nombre: "Pelota Head TOUR",
        imagen: "/img/pelotaheadtour.jpg",
        precio: 7,
        cantidad: 1,
    },
    {
        id: "Pelota4",
        nombre: "Pelota Odea",
        imagen: "/img/pelotaodea.jpeg",
        precio: 3,
        cantidad: 1,
    },
    {
        id: "Pelota5",
        nombre: "Pelota Penn T",
        imagen: "/img/pelotapenntour.jpg",
        precio: 6,
        cantidad: 1,
    },
    {
        id: "Pelota6",
        nombre: "Pelota Tecnifibre",
        imagen: "/img/pelotatecnifibre.jpg",
        precio: 4,
        cantidad: 1,
    },
    {
        id: "Pelota7",
        nombre: "Pelota Topper",
        imagen: "/img/pelotatopper.jpg",
        precio: 6,
        cantidad: 1,
    },
    {
        id: "Pelota8",
        nombre: "Pelota Tretorn",
        imagen: "/img/pelotatretorn.webp",
        precio: 5,
        cantidad: 1,
    },
    {
        id: "Pelota9",
        nombre: "Pelota Wilson",
        imagen: "/img/pelotawilson.jpg",
        precio: 4,
        cantidad: 1,
    },

    {
        id: "Raquetero1",
        nombre: "Raquetero Babolat",
        imagen: "/img/rababolataero.jpg",
        precio: 150,
        cantidad: 1,
    },
    
    {
        id: "Raquetero3",
        nombre: "Raquetero Head W",
        imagen: "/img/raheadwhite.jpg",
        precio: 160,
        cantidad: 1,
    },

    {
        id: "Raquetero4",
        nombre: "Raquetero Prince",
        imagen: "/img/raprince.jpg",
        precio: 100,
        cantidad: 1,
    },
    {
        id: "Raquetero5",
        nombre: "Raquetero Wilson",
        imagen: "/img/rawilson.webp",
        precio: 180,
        cantidad: 1,
    },
    {
        id: "Raquetero6",
        nombre: "Raquetero Yonex",
        imagen: "/img/rayonex.webp",
        precio: 130,
        cantidad: 1,
    },

];*/

/*ARRASTRO LOS PRODUCTOS EN APP.JS EN LA FUNCION DE FETCH*/